CREATE TABLE GIOCATORE(
  NOME VARCHAR(30)                        NOT NULL ,
  COGNOME VARCHAR(30)                     NOT NULL ,
  CODICE_FISCALE VARCHAR(16)              NOT NULL ,
  USER_NAME VARCHAR(50)                   NOT NULL,
  MAIL VARCHAR(50)                   	  NOT NULL,
  PASSWORD VARCHAR(50)                    NOT NULL,

  PRIMARY KEY(CODICE_FISCALE)
);

CREATE TABLE SQUADRA(
  NOME VARCHAR (255)                      NOT NULL  ,
  REFERENTE      VARCHAR(16)              		    ,

  PRIMARY KEY(NOME)
);

CREATE TABLE FORMAZIONE(
  NOME_SQUADRA            VARCHAR (255)   NOT NULL ,
  CODICE_FISCALE_GIOCATORE VARCHAR(16)    NOT NULL ,

  PRIMARY KEY (NOME_SQUADRA,CODICE_FISCALE_GIOCATORE)
);

CREATE TABLE PARTITA(

  DATA_PARTITA DATE NOT NULL                          ,
  ORA		VARCHAR(7) NOT NULL ,
  CAMPO_ID VARCHAR(30) NOT NULL                      ,
  NOME_SQUADRA_SFIDATA    VARCHAR (255)                  ,
  NOME_SQUADRA_SFIDANTE   VARCHAR (255)     NOT NULL     ,

  PRIMARY KEY(  DATA_PARTITA ,ORA	,CAMPO_ID)
);

-- vincoli
ALTER TABLE FORMAZIONE ADD
FOREIGN KEY(CODICE_FISCALE_GIOCATORE)   REFERENCES GIOCATORE(CODICE_FISCALE);
ALTER TABLE FORMAZIONE ADD
FOREIGN KEY(NOME_SQUADRA)                 REFERENCES SQUADRA(NOME);

ALTER TABLE PARTITA ADD
FOREIGN KEY(NOME_SQUADRA_SFIDATA)         REFERENCES SQUADRA(NOME);
ALTER TABLE PARTITA ADD
FOREIGN KEY(NOME_SQUADRA_SFIDANTE)        REFERENCES SQUADRA(NOME);

ALTER TABLE SQUADRA ADD
FOREIGN KEY(REFERENTE)   REFERENCES GIOCATORE(CODICE_FISCALE);

CREATE UNIQUE INDEX unique_USER_NAME ON GIOCATORE ( USER_NAME );
CREATE UNIQUE INDEX unique_MAIL ON GIOCATORE ( MAIL );

